export default {
    primaryColor: '#1e272c',
    primaryColorHalfOpaque: 'rgba(30, 39, 44, 0.5)',
    secondaryColor: '#36474f',
    highlightColor: '#f6ab27',
    menuTextColor: '#838c91',
    backgroundColor: '#eceff2',
    secondaryBackgroundColor: '#fafafa',
    baseBorderColor: '#e0e0e0',
    watermarkColor: 'darkgrey',
    disabledColor: '#f5f4f4',
    disabledOnGreyColor: '#afafaf',
    baseBlueColor: '#448ccb',
    basePurpleColor: '#7985ce',
    basePinkColor: '#ff3a4e',
    baseGrayColor: '#565656',
    baseGreenColor: '#b7cbc0',
    suggestionColor: '#eceff2',
    mentionColor: '#575f67',

    redCircleColor: '#ff3a4e',
    blueCircleColor: '#448ccb',
    greenCircleColor: 'green',
    yellowCircleColor: '#ffd200',
    greyCircleColor: '#646464',
    
    glassPaneColor: 'rgba(250, 250, 250, 0.5)',

    previewLineHeight: 1.571,
    mainAppPadding: 35,
    messageLetterSpacing: '0.025em',

    backZIndex: 10,
    dragHandleZIndex: 13,
    mentionSuggestionsZIndex: 14,
    toAutosuggestZIndex: 15,
    fullItemBlurZIndex: 40,
    fullItemZIndex: 50,
    previewInlineReplyZIndex: 100,
    modalOverlayZIndex: 140,
    modalZIndex: 150
}
