module.exports = [
    require('./thing-command'),
    require('./event'),
    require('./follow-up'),
    require('./to-do'),
    require('./mentions'),
    require('./whats-new'),
    require('./thing-page'),
    require('./email'),
    require('./email-page'),
    require('./email-command'),
    require('./github'),
    require('./message-box'),
    require('./auth'),
    require('./contacts'),
    require('./glass-pane'),
    require('./inline-message'),
    require('./slack')
]
